package com.routeintelligence.routeapi.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.util.List;

/**
 * Entity representing a user of the system.
 * A user can create multiple routes.
 */
@Entity
@Table(name = "users")
@Getter
@Setter
public class User {

    /**
     * Primary key of the user.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Username chosen by the user.
     * Must be unique and not null.
     */
    @Column(nullable = false, unique = true)
    private String username;

    /**
     * Email address of the user.
     * Must be unique and not null.
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * Relationship with Route.
     * One user can have multiple routes.
     */
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL)
    private List<Route> routes;

    /**
     * Default constructor required by JPA.
     */
    public User() {}

    /**
     * Constructor used for creating new users.
     */
    public User(String username, String email) {
        this.username = username;
        this.email = email;
    }
}
